version: '3'

services:
  api:
    build: ./api
    container_name: api
    volumes:
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - redis
    networks:
      - innyx-network

  mysql:
    build: ./docker/mysql
    container_name: mysql
    restart: always
    tty: true
    ports:
        - "33066:3306"
    volumes:
        - ./docker/dbdata:/var/lib/mysql
        - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root
    networks:
        - innyx-network

  # app:
  #   build: ./app
  #   container_name: app
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - innyx-network

  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    depends_on:
      - api
      #- app
    networks:
      - innyx-network

  redis:
      image: redis:alpine
      container_name: redis
      networks:
          - innyx-network

networks:
  innyx-network:
    driver: bridge
